using System.Globalization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Primitives;
using Microsoft.Net.Http.Headers;

namespace CommonVisionNodes.Server.Services;

/// <summary>
/// Selects and serves Brotli or gzip sidecars generated by the WebAssembly publish pipeline.
/// </summary>
public static class PrecompressedStaticFileResponder
{
	private const string BrotliEncoding = "br";
	private const string GzipEncoding = "gzip";
	private const string ImmutableCacheControl = "public, max-age=31536000, immutable";
	private const string RevalidateCacheControl = "no-cache";

	/// <summary>
	/// Attempts to respond with a precompressed sidecar for the requested static asset.
	/// </summary>
	/// <param name="context">Current HTTP context.</param>
	/// <param name="fileProvider">Provider rooted at the deployed WebAssembly application.</param>
	/// <param name="contentTypeProvider">Content-type mapping for the uncompressed resource path.</param>
	/// <returns><c>true</c> when a compressed sidecar was sent; otherwise <c>false</c>.</returns>
	public static async Task<bool> TryServeAsync(
		HttpContext context,
		IFileProvider fileProvider,
		IContentTypeProvider contentTypeProvider)
	{
		if (!HttpMethods.IsGet(context.Request.Method) && !HttpMethods.IsHead(context.Request.Method) ||
			context.Request.Headers.ContainsKey(HeaderNames.Range))
		{
			return false;
		}

		var relativePath = GetRelativePath(context.Request.Path);
		if (relativePath is null)
			return false;

		var originalFile = fileProvider.GetFileInfo(relativePath);
		if (!originalFile.Exists || originalFile.IsDirectory)
			return false;

		foreach (var encoding in GetPreferredEncodings(context.Request.Headers.AcceptEncoding))
		{
			var sidecarFile = fileProvider.GetFileInfo($"{relativePath}.{GetSidecarExtension(encoding)}");
			if (!sidecarFile.Exists || sidecarFile.IsDirectory)
				continue;

			var lastModified = TruncateToHttpDatePrecision(sidecarFile.LastModified);
			var entityTag = CreateEntityTag(sidecarFile.Length, lastModified);
			if (IsNotModified(context.Request, entityTag, lastModified))
			{
				PrepareNotModifiedResponse(context.Response, context.Request.Path, encoding, entityTag, lastModified);
				return true;
			}

			PrepareResponse(
				context.Response,
				context.Request.Path,
				contentTypeProvider,
				sidecarFile.Length,
				encoding,
				entityTag,
				lastModified);
			if (HttpMethods.IsHead(context.Request.Method))
				return true;

			if (sidecarFile.PhysicalPath is not null)
			{
				await context.Response.SendFileAsync(sidecarFile.PhysicalPath, context.RequestAborted);
			}
			else
			{
				await using var stream = sidecarFile.CreateReadStream();
				await stream.CopyToAsync(context.Response.Body, context.RequestAborted);
			}

			return true;
		}

		return false;
	}

	/// <summary>
	/// Applies the cache policy shared by compressed and uncompressed WebAssembly static assets.
	/// </summary>
	public static void ApplyCacheHeaders(HttpResponse response, PathString requestPath)
	{
		response.Headers[HeaderNames.CacheControl] = IsFingerprintedFrameworkAsset(requestPath)
			? ImmutableCacheControl
			: RevalidateCacheControl;
		response.Headers.Append(HeaderNames.Vary, HeaderNames.AcceptEncoding);
	}

	private static void PrepareResponse(
		HttpResponse response,
		PathString requestPath,
		IContentTypeProvider contentTypeProvider,
		long contentLength,
		string contentEncoding,
		string entityTag,
		DateTimeOffset lastModified)
	{
		response.StatusCode = StatusCodes.Status200OK;
		response.ContentLength = contentLength;
		ApplyRepresentationHeaders(response, requestPath, contentEncoding, entityTag, lastModified);
		response.ContentType = contentTypeProvider.TryGetContentType(requestPath, out var contentType)
			? contentType
			: "application/octet-stream";
	}

	private static void PrepareNotModifiedResponse(
		HttpResponse response,
		PathString requestPath,
		string contentEncoding,
		string entityTag,
		DateTimeOffset lastModified)
	{
		response.StatusCode = StatusCodes.Status304NotModified;
		ApplyRepresentationHeaders(response, requestPath, contentEncoding, entityTag, lastModified);
	}

	private static void ApplyRepresentationHeaders(
		HttpResponse response,
		PathString requestPath,
		string contentEncoding,
		string entityTag,
		DateTimeOffset lastModified)
	{
		response.Headers[HeaderNames.ContentEncoding] = contentEncoding;
		response.Headers[HeaderNames.ETag] = entityTag;
		response.Headers[HeaderNames.LastModified] = lastModified.ToString("R", CultureInfo.InvariantCulture);
		ApplyCacheHeaders(response, requestPath);
	}

	private static string? GetRelativePath(PathString requestPath)
	{
		var path = requestPath.Value;
		if (string.IsNullOrEmpty(path) ||
			path.EndsWith(".br", StringComparison.OrdinalIgnoreCase) ||
			path.EndsWith(".gz", StringComparison.OrdinalIgnoreCase))
		{
			return null;
		}

		var relativePath = path.TrimStart('/');
		return relativePath.Contains("..", StringComparison.Ordinal) || relativePath.Contains('\\')
			? null
			: relativePath;
	}

	private static IEnumerable<string> GetPreferredEncodings(StringValues acceptEncoding)
	{
		var brotliQuality = GetQuality(acceptEncoding, BrotliEncoding);
		var gzipQuality = GetQuality(acceptEncoding, GzipEncoding);

		if (brotliQuality <= 0 && gzipQuality <= 0)
			yield break;

		if (brotliQuality >= gzipQuality && brotliQuality > 0)
		{
			yield return BrotliEncoding;
			if (gzipQuality > 0)
				yield return GzipEncoding;
			yield break;
		}

		if (gzipQuality > 0)
			yield return GzipEncoding;
		if (brotliQuality > 0)
			yield return BrotliEncoding;
	}

	private static double GetQuality(StringValues acceptEncoding, string requestedEncoding)
	{
		double? exactQuality = null;
		double? wildcardQuality = null;

		foreach (var value in acceptEncoding)
		{
			if (string.IsNullOrWhiteSpace(value))
				continue;

			foreach (var encoding in value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
			{
				var parts = encoding.Split(';', StringSplitOptions.TrimEntries);
				if (parts.Length == 0)
					continue;

				var quality = GetSpecifiedQuality(parts);
				if (parts[0].Equals(requestedEncoding, StringComparison.OrdinalIgnoreCase))
					exactQuality = quality;
				else if (parts[0] == "*")
					wildcardQuality = quality;
			}
		}

		return exactQuality ?? wildcardQuality ?? 0;
	}

	private static double GetSpecifiedQuality(string[] parts)
	{
		foreach (var parameter in parts.Skip(1))
		{
			if (!parameter.StartsWith("q=", StringComparison.OrdinalIgnoreCase))
				continue;

			return double.TryParse(
				parameter.AsSpan(2),
				NumberStyles.AllowDecimalPoint,
				CultureInfo.InvariantCulture,
				out var quality)
				? Math.Clamp(quality, 0, 1)
				: 0;
		}

		return 1;
	}

	private static string GetSidecarExtension(string contentEncoding)
		=> contentEncoding == BrotliEncoding ? "br" : "gz";

	private static bool IsNotModified(HttpRequest request, string entityTag, DateTimeOffset lastModified)
	{
		if (request.Headers.TryGetValue(HeaderNames.IfNoneMatch, out var ifNoneMatch))
			return MatchesIfNoneMatch(ifNoneMatch, entityTag);

		if (!request.Headers.TryGetValue(HeaderNames.IfModifiedSince, out var ifModifiedSince) ||
			!DateTimeOffset.TryParse(
				ifModifiedSince.ToString(),
				CultureInfo.InvariantCulture,
				DateTimeStyles.AllowWhiteSpaces | DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
				out var modifiedSince))
		{
			return false;
		}

		return lastModified <= TruncateToHttpDatePrecision(modifiedSince);
	}

	private static bool MatchesIfNoneMatch(StringValues candidates, string entityTag)
	{
		foreach (var headerValue in candidates)
		{
			if (string.IsNullOrWhiteSpace(headerValue))
				continue;

			foreach (var candidate in headerValue.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
			{
				if (candidate == "*")
					return true;

				var normalizedCandidate = candidate.StartsWith("W/", StringComparison.OrdinalIgnoreCase)
					? candidate[2..].TrimStart()
					: candidate;
				if (normalizedCandidate.Equals(entityTag, StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}

	private static DateTimeOffset TruncateToHttpDatePrecision(DateTimeOffset value)
	{
		var utcValue = value.UtcDateTime;
		return new DateTimeOffset(
			utcValue.AddTicks(-(utcValue.Ticks % TimeSpan.TicksPerSecond)),
			TimeSpan.Zero);
	}

	private static string CreateEntityTag(long contentLength, DateTimeOffset lastModified)
		=> $"\"{lastModified.UtcDateTime.Ticks:x}-{contentLength:x}\"";

	private static bool IsFingerprintedFrameworkAsset(PathString requestPath)
	{
		if (!requestPath.StartsWithSegments("/_framework", StringComparison.OrdinalIgnoreCase))
			return false;

		var fileName = Path.GetFileName(requestPath.Value);
		if (string.IsNullOrEmpty(fileName))
			return false;

		var extensionSeparator = fileName.LastIndexOf('.');
		if (extensionSeparator <= 0)
			return false;

		var fingerprintSeparator = fileName.LastIndexOf('.', extensionSeparator - 1);
		if (fingerprintSeparator < 0 || extensionSeparator - fingerprintSeparator != 11)
			return false;

		foreach (var character in fileName.AsSpan(fingerprintSeparator + 1, 10))
		{
			if ((character < 'a' || character > 'z') && (character < '0' || character > '9'))
				return false;
		}

		return true;
	}
}
