<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoFeatures>SkiaRenderer</UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonVisionNodes.Contracts\CommonVisionNodes.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\CvbImageDisplay.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\PreviewImagePresenter.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>
